mysql:
  user: 'root'
  password: 'asdfasdf'
  host: localhost
  database: pearlpearl
  port: 3306
  poolsize: 10
  connectionTimeout: 10000
  idleTimout: 600000
  maxLifetime: 7200000

enabledBehaviors:
  EXILE: 10
  END: 5
  BASTION_BANISH: 1
