name: ${project.name}
main: com.github.lazersmoke.PearlPearl.PearlPearl
author: Lazersmoke
version: ${project.version}
depend: [CivModCore, NameLayer]
softdepend: [CombatTagPlus, Bastion]
commands:
  ppaggro:
    aliases: [ppa]
    permission: pearlpearl.admin
  ppbehave:
    aliases: [ppb]
    permission: pearlpearl.public
  ppcheck:
    aliases: [ppc]
    permission: pearlpearl.admin
  ppoverview:
    aliases: [ppo]
    permission: pearlpearl.admin
  ppsmite:
    aliases: [pps]
    permission: pearlpearl.admin
  ppverify:
    aliases: [ppv]
    permission: pearlpearl.public
  ppunleash:
    aliases: [ppu]
    permission: pearlpearl.public
  ppzap:
    aliases: [ppz]
    permission: pearlpearl.admin
permissions:
  pearlpearl.public:
    default: true
  pearlpearl.admin:
    default: op
