name: ${project.name}
main: com.github.lazersmoke.PearlPearl.PearlPearl
author: Lazersmoke
version: ${project.version}
depend: [CivModCore, NameLayer]
softdepend: [CombatTagPlus, Bastion]
commands:
    ppunleash:
        permission: pearlpearl.public
    ppverify:
        permission: pearlpearl.public
    ppbehave:
        permission: pearlpearl.public
    ppcheck:
        permission: pearlpearl.admin
    ppaggro:
        permission: pearlpearl.admin
    ppsmite:
        permission: pearlpearl.admin
permissions:
    pearlpearl.public:
        default: true
    pearlpearl.admin:
        default: op
